# coding: utf-8

"""
    ToDo API

    The ToDo API manages a ToDo list.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.to_do_handler_api import ToDoHandlerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestToDoHandlerApi(unittest.TestCase):
    """ToDoHandlerApi unit test stubs"""

    def setUp(self):
        self.api = ToDoHandlerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_todo_get(self):
        """Test case for v1_todo_get

        Get all ToDo objects  # noqa: E501
        """
        pass

    def test_v1_todo_put(self):
        """Test case for v1_todo_put

        Creat a new ToDo object  # noqa: E501
        """
        pass

    def test_v1_todo_todo_id_delete(self):
        """Test case for v1_todo_todo_id_delete

        Delete an existing ToDo object  # noqa: E501
        """
        pass

    def test_v1_todo_todo_id_get(self):
        """Test case for v1_todo_todo_id_get

        Get a single ToDo object  # noqa: E501
        """
        pass

    def test_v1_todo_todo_id_put(self):
        """Test case for v1_todo_todo_id_put

        Update an existing ToDo object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
