# coding: utf-8

"""
    ToDo API

    The ToDo API manages a ToDo list.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.to_do import ToDo  # noqa: E501
from swagger_client.rest import ApiException


class TestToDo(unittest.TestCase):
    """ToDo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToDo(self):
        """Test ToDo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.to_do.ToDo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
