# coding: utf-8

# flake8: noqa
"""
    ToDo API

    The ToDo API manages a ToDo list.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.to_do import ToDo
